"""empty message

Revision ID: 258c5a9e1c27
Revises: 
Create Date: 2020-10-29 07:48:08.180524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258c5a9e1c27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'houses', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'houses', type_='foreignkey')
    op.drop_column('houses', 'owner_id')
    # ### end Alembic commands ###
